version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinic_management
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8090:8080
